services:

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: todo-go
    environment:
      DB_HOST: otel-postgres
      DB_PORT: 5432
      DB_USER: gotodo
      DB_PASSWORD: gotodo
      DB_NAME: gotodo
    ports:
      - "8080:8080"

volumes:
  postgres-data:

