kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: hello-java-undertow
  labels:
    app: hello-java-undertow
    app.kubernetes.io/component: hello-java-undertow
    app.kubernetes.io/instance: hello-java-undertow
    app.kubernetes.io/name: hello-java-undertow
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'hello-java-undertow:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'java:openjdk-17-ubi8'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/hash-as673/spring-demo-maven-jboss-jdk17.git'
    contextDir: /
  runPolicy: Serial
