apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 02-Quarkus-hello-world/k8s-manifests/00-manifests/jvm/deployment.yaml
- 02-Quarkus-hello-world/k8s-manifests/00-manifests/jvm/secret.yaml
- 02-Quarkus-hello-world/k8s-manifests/00-manifests/jvm/service.yaml
- 02-Quarkus-hello-world/k8s-manifests/00-manifests/jvm/ingress.yaml